### ISSUE TITLE
Implicitly requiring `test_init.rb` (and friends)

### ISSUE THREAD

**Issue by tomdalling** [test-bench/test-bench#8]
One of the annoyances I have with explicitly writing `require_relative '../test_init'` at the top of every file is that it couples the file to its position in the directory structure. Moving the test file to a deeper or shallower directory breaks it. Also, it's a little bit of friction every time you create a new test file, which nudges people towards fewer-but-larger files instead of the "Use Small and Focused Test Files" tip.

To get around this in RSpec, I would create a `.rspec` file that contains `--require spec/spec_helper`, or possibly add the same CLI arg to a `bin/test` script.

What's the best way to do this in TestBench? I can probably cobble something together using `TestBench::Run`, but I was wondering if you are considering adding something like this to the `bench` executable.

**Comment by ntl** [comment]
Thanks for the issue!

Unfortunately, there hasn't been any mechanism discovered to reduce this boilerplate. Anything added to TestBench to remove the need for the `require_relative` would inevitably remove the capability of running test files directly, i.e. `ruby path/to/test_file.rb`.

If you don't mind losing the ability to run test files with just ruby, there is a solution. You can embed the CLI inside the project, and load your test init file there:

```
# Begin test/bench.rb

require_relative './test_init'

TestBench::CLI.("test/automated")
```

This file will work just like the `bench` executable, so you can pass e.g. directories and individual test files to narrow what gets run.

If you _always_ use `ruby test/bench.rb` to launch your test files, then you could remove the `require_relative` in each file.

Please let me know if this works for you. It also might make for a handy [recipe](http://test-bench.software/user-guide/recipes.html).

**Comment by ntl** [comment]
P.S. I apologize for the delay in response, I hadn't yet figured out how to get proper notifications for issues filed to the `test-bench` organization. It dawned on me that I can just watch the repositories (duh!).

**Comment by tomdalling** [comment]
> If you don't mind losing the ability to run test files with just ruby, there is a solution. You can embed the CLI inside the project

In my Vim setup, I never use the plain `ruby` executable to run tests, so I think I will give this a shot. Recently I've become interested in how friction affects developer behaviour, so I'm trying to actively experiment with things like this.

> I apologize for the delay in response

No apologies are expected! I'm a big believer in [maintainers' rights](https://gist.github.com/richhickey/1563cddea1002958f96e7ba9519972d9). I just wanted to suss out if you're interested in feedback, because I'm happy to help improve the first-time developer experience by reporting things I'm stumbling over.
