### ISSUE TITLE
How do you share assertion methods?

### ISSUE THREAD

**Issue by tomdalling** [test-bench/test-bench#9]
For example, if I have a custom assertion method...

```ruby
module MyCustomAssertions
  def assert_json(...)
    # ...
  end
end
```

... what is the recommended way to make it available for use in different test files? I've worked out that `extend` does the trick, but I didn't find any examples in the docs.

P.S. Let me know if these GH issues are annoying. I don't want to be a burden on maintainers.

**Comment by ntl** [comment]
We tend to add custom assertions to specific fixtures classes where they are relevant; e.g. a fixture that tests an HTTP request handler might have an `assert_json_response` method, for instance. The assertions offered by TestBench out of the box are limited to just the assertions that are generally useful to every project.

The TestBench::Fixture library is packaged separately from TestBench specifically in order to ensure that library and framework authors can ship test code alongside your gems, without causing users of those libraries to take a transitive "production" dependency on a test framework.

So, feel free to include assertions modules and fixture classes with your libraries, or in supplemental TestBench specific companion libraries. As an example, Eventide is taking the [latter approach](https://github.com/eventide-project/messaging-fixtures/).

> P.S. Let me know if these GH issues are annoying. I don't want to be a burden on maintainers.

These issues are both welcome and highly appreciated! I wish it hadn't taken me a week to reply to the last one!

**Comment by tomdalling** [comment]
I think my mistake was assuming that fixtures are "RSpec shared examples as a class", but looking at the Eventide fixtures I can see that they are more than that.

I refactored a [test file](https://github.com/tomdalling/memex/blob/aaa74c75e8eeb2dba6bc363ea54ac32d69749b46/test/automated/zettel/hashtag_query.rb) to try and use [a fixture](https://github.com/tomdalling/memex/blob/aaa74c75e8eeb2dba6bc363ea54ac32d69749b46/test/support/hashtag_query_fixture.rb) the intended way. It produces [fairly readable output](https://gist.github.com/tomdalling/5cfc4548146695c6ee6bfc3910df3f64). Is this roughly how fixtures are intended to be used?

I also worked out a way to use a [default fixture for the test suite](https://github.com/tomdalling/memex/blob/aaa74c75e8eeb2dba6bc363ea54ac32d69749b46/test/test_init.rb#L11-L27). Be prepared: it might offend your testing sensibilities 😄 . I haven't actually added any assertion methods to it yet, but I want to try it out.

**Comment by ntl** [comment]
> Is this roughly how fixtures are intended to be used?

The mechanics are fairly close. A couple points:

- In the `HashtagQuery` fixture, you might want to include the `query` itself as a detail. That way, if any test fails, the user can see what it's being compared against.
- It's obviously your call as to whether you find value in it for your project, but in the spirit of taking TestBench for a spin, you might want to explore testing `HashtagQuery` itself. You should be able to prove that its tests pass when they're supposed to pass, and fail when they're supposed to fail. This is an important part of TestBench::Fixtures -- they're test abstractions designed to validate countless implementations, so a mistake in a test abstraction is like a mistake in a die casting in a manufacturing plant. There's a relevant section in the [user guide](http://test-bench.software/user-guide/fixtures.html#testing-fixtures)
- The default fixture might be a bit more than what's needed. You should be able to extend TestBench::Fixture itself if you want to add methods to every fixture:

 ```ruby
 module SomeExtension
   def some_new_method
   end
 end

 TestBench::Fixture.include(SomeExtension)
 ```

 I can't say that is recommended from a design perspective as it specializes something that's extremely general purpose, but TestBench should allow for that kind of extension.

- There are indeed a good number of aesthetic, structural, and fundamental differences from how we typically set up projects with TestBench -- we don't use `test/support` directories, for instance, as our libraries themselves are required to ship with all necessary affordances for testing. However, another core tenet of TestBench is that it should always stay out of your way and let you control it as you wish. Nothing opinionated or convention over configuration here :)

**Comment by tomdalling** [comment]
Thanks for the pointers. Now I'm thinking that `HashtagQueryFixture` shouldn't be a fixture at all, because it's only testing a single implementation. I've replaced it with a couple of custom assertion methods that are local to the test file, but I think I understand how to write a reusable fixture when I need one, now. Like, I could add one to ValueSemantics for testing value classes, in which case I would want to test the fixture properly.

**Comment by ntl** [comment]
Fixture classes can also be useful to generalize common assertions -- any generalization of test code is likely suitable for going in a fixture class -- so I can't say your usage was off target. It certainly didn't jump out at me as a misappropriation, but I don't know enough about the implementation to really say anything definitively.
